// v18.0 Frontend Features - Chat Folders, Branching, Search, Quick Replies, API Keys, Export, Scheduled Messages
const API18='';

// Chat Folders
let userFolders=[];
async function loadFolders(){try{const r=await fetch(API18+'/api/folders',{headers:{'Authorization':'Bearer '+getToken()}});if(r.ok){const d=await r.json();userFolders=d.folders||[];renderFolders()}}catch{}}
function renderFolders(){const c=document.getElementById('folderList');if(!c)return;c.innerHTML=userFolders.map(f=>'<div class="folder-item" onclick="filterByFolder(\''+f.id+'\')" style="display:flex;align-items:center;gap:8px;padding:6px 12px;border-radius:8px;cursor:pointer;font-size:.84rem"><svg width="14" height="14" style="color:'+f.color+'"><use href="#icon-folder"/></svg><span>'+f.name+'</span><span style="margin-left:auto;font-size:.72rem;color:var(--ink4)">'+(f.chatIds||[]).length+'</span></div>').join('')}
function showNewFolderModal(){showModal('<h2>New Folder</h2><div class="fg"><label>Folder Name</label><input class="input" id="folderName" placeholder="e.g. Work, Research"></div><div class="fg"><label>Color</label><input class="input" type="color" id="folderColor" value="#c84b09"></div><button class="btn-accent" onclick="createFolder()">Create Folder</button>');}
async function createFolder(){const name=document.getElementById('folderName').value;const color=document.getElementById('folderColor').value;if(!name)return;try{await fetch(API18+'/api/folders',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+getToken()},body:JSON.stringify({name,color})});loadFolders();closeModal();showToast('Folder created')}catch{showToast('Failed')}}
async function filterByFolder(folderId){const f=userFolders.find(x=>x.id===folderId);if(!f)return;showToast('Filtering: '+f.name)}

// Conversation Search
function showSearchModal(){showModal('<h2>Search Conversations</h2><div class="fg"><input class="input" id="searchQuery" placeholder="Search all messages..." onkeyup="if(event.key===Enter)searchChats()"></div><div id="searchResults" style="max-height:300px;overflow-y:auto"></div><button class="btn-accent" onclick="searchChats()" style="margin-top:8px">Search</button>');}
async function searchChats(){const q=document.getElementById('searchQuery').value;if(!q)return;try{const r=await fetch(API18+'/api/chats/search?q='+encodeURIComponent(q),{headers:{'Authorization':'Bearer '+getToken()}});if(r.ok){const d=await r.json();document.getElementById('searchResults').innerHTML=(d.results||[]).map(r=>'<div style="padding:10px;border:1px solid var(--border);border-radius:8px;margin-bottom:8px;cursor:pointer" onclick="loadChat(\''+r.chatId+'\')"><strong>'+r.title+'</strong><div style="font-size:.78rem;color:var(--ink3)">'+r.totalMatches+' matches</div>'+(r.matches||[]).slice(0,2).map(m=>'<div style="font-size:.8rem;color:var(--ink4);margin-top:4px">'+m.content.substring(0,100)+'...</div>').join('')+'</div>').join('')||'<div style="color:var(--ink3);text-align:center;padding:20px">No results found</div>'}}catch{}}

// Quick Replies
let userQuickReplies=[];
async function loadQuickReplies(){try{const r=await fetch(API18+'/api/quick-replies',{headers:{'Authorization':'Bearer '+getToken()}});if(r.ok){const d=await r.json();userQuickReplies=d.quickReplies||[]}}catch{}}
function showQuickRepliesModal(){showModal('<h2>Quick Replies</h2><div id="qrList" style="margin-bottom:16px">'+userQuickReplies.map(r=>'<div style="display:flex;align-items:center;gap:8px;padding:8px;border:1px solid var(--border);border-radius:8px;margin-bottom:8px"><div style="flex:1"><strong>/'+r.shortcut+'</strong><div style="font-size:.78rem;color:var(--ink3)">'+r.title+'</div></div><button onclick="useQuickReply(\''+r.shortcut+'\')" style="background:var(--accent);color:#fff;border:none;border-radius:6px;padding:4px 8px;cursor:pointer;font-size:.78rem">Use</button></div>').join('')+'</div><div class="fg"><input class="input" id="qrShortcut" placeholder="Shortcut (e.g. thanks)"></div><div class="fg"><input class="input" id="qrTitle" placeholder="Title"></div><div class="fg"><textarea class="input" id="qrContent" rows="3" placeholder="Response text"></textarea></div><button class="btn-accent" onclick="createQuickReply()">Save Quick Reply</button>');}
async function createQuickReply(){const shortcut=document.getElementById('qrShortcut').value;const title=document.getElementById('qrTitle').value;const content=document.getElementById('qrContent').value;if(!shortcut||!content)return;try{await fetch(API18+'/api/quick-replies',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+getToken()},body:JSON.stringify({shortcut,title,content})});loadQuickReplies();closeModal();showToast('Quick reply saved')}catch{}}
function useQuickReply(shortcut){const r=userQuickReplies.find(x=>x.shortcut===shortcut);if(r){document.getElementById('messageInput').value=r.content;closeModal()}}

// API Keys
function showApiKeysModal(){showModal('<h2>API Keys</h2><p style="font-size:.84rem;color:var(--ink3);margin-bottom:16px">Manage API keys for programmatic access.</p><div id="apiKeysList" style="margin-bottom:16px"></div><div class="fg"><input class="input" id="newKeyName" placeholder="Key name"></div><button class="btn-accent" onclick="createApiKey()">Generate New Key</button>');fetch(API18+'/api/api-keys',{headers:{'Authorization':'Bearer '+getToken()}}).then(r=>r.json()).then(d=>{document.getElementById('apiKeysList').innerHTML=(d.apiKeys||[]).map(k=>'<div style="display:flex;align-items:center;gap:8px;padding:8px;border:1px solid var(--border);border-radius:8px;margin-bottom:8px"><div style="flex:1"><strong>'+k.name+'</strong><div style="font-size:.78rem;color:var(--ink3);font-family:monospace">'+k.key+'</div></div><button onclick="deleteApiKey(\''+k.id+'\')" style="background:transparent;color:#ef4444;border:1px solid #ef4444;border-radius:6px;padding:4px 8px;cursor:pointer;font-size:.78rem">Revoke</button></div>').join('')||'<div style="color:var(--ink3);text-align:center">No API keys yet</div>'}).catch(()=>{})}
async function createApiKey(){const name=document.getElementById('newKeyName').value;if(!name)return;try{const r=await fetch(API18+'/api/api-keys',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+getToken()},body:JSON.stringify({name})});if(r.ok){const d=await r.json();showModal('<h2>API Key Created</h2><p style="margin:12px 0">Copy this key now — it won\'t be shown again:</p><div style="background:var(--bg);padding:12px;border-radius:8px;font-family:monospace;font-size:.84rem;word-break:break-all;border:1px solid var(--border)">'+d.apiKey.key+'</div><button class="btn-accent" onclick="closeModal()" style="margin-top:12px">Done</button>')}}catch{}}
async function deleteApiKey(id){if(!confirm('Revoke this key?'))return;await fetch(API18+'/api/api-keys/'+id,{method:'DELETE',headers:{'Authorization':'Bearer '+getToken()}});showApiKeysModal()}

// Export Data
function exportMyData(){window.open(API18+'/api/export?token='+getToken());showToast('Preparing download...')}

// Scheduled Messages
function showScheduledModal(){showModal('<h2>Scheduled Messages</h2><p style="font-size:.84rem;color:var(--ink3);margin-bottom:16px">Schedule messages to be sent later.</p><div class="fg"><label>Message</label><textarea class="input" id="schedContent" rows="3" placeholder="What to send"></textarea></div><div class="fg"><label>Send at</label><input class="input" type="datetime-local" id="schedTime"></div><button class="btn-accent" onclick="scheduleMessage()">Schedule</button>');}
async function scheduleMessage(){const content=document.getElementById('schedContent').value;const scheduledAt=document.getElementById('schedTime').value;if(!content||!scheduledAt)return;try{await fetch(API18+'/api/scheduled',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+getToken()},body:JSON.stringify({chatId:currentChatId,content,scheduledAt})});closeModal();showToast('Message scheduled')}catch{}}

// Chat Tags
function addTagToChat(){const tag=prompt('Enter tag:');if(!tag||!currentChatId)return;fetch(API18+'/api/chats/'+currentChatId+'/tags',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+getToken()},body:JSON.stringify({tag})}).then(()=>showToast('Tag added'))}

// Undo Last Message
async function undoLastMessage(){if(!currentChatId)return;try{const r=await fetch(API18+'/api/chats/'+currentChatId+'/last-message',{method:'DELETE',headers:{'Authorization':'Bearer '+getToken()}});if(r.ok){const d=await r.json();if(d.removed){chatMessages=chatMessages.filter((_,i)=>i!==chatMessages.length-1);renderMessages();showToast('Message undone')}}}catch{}}

// Regenerate Response
async function regenerateResponse(){if(!currentChatId)return;try{const r=await fetch(API18+'/api/chats/'+currentChatId+'/regenerate',{method:'POST',headers:{'Authorization':'Bearer '+getToken()}});if(r.ok){const d=await r.json();chatMessages[chatMessages.length-1]=d.message;renderMessages();showToast('Response regenerated')}}catch{}}

// Model Performance
function showModelMetrics(){fetch(API18+'/api/model-metrics').then(r=>r.json()).then(d=>{showModal('<h2>Model Performance</h2><div style="display:grid;gap:12px;margin-top:16px">'+d.models.map(m=>'<div style="padding:12px;border:1px solid var(--border);border-radius:8px"><div style="display:flex;justify-content:space-between;margin-bottom:8px"><strong>'+m.name+'</strong><span style="color:var(--accent)">'+m.satisfaction+'/5</span></div><div style="display:flex;gap:16px;font-size:.78rem;color:var(--ink3)"><span>Latency: '+m.latency+'ms</span><span>Uptime: '+m.uptime+'%</span><span>Chats: '+m.totalChats.toLocaleString()+'</span></div></div>').join('')+'</div><button class="btn-accent" onclick="closeModal()" style="margin-top:16px">Close</button>')})}

// Typing indicator
let typingTimeout;
function sendTyping(){if(!currentChatId)return;clearTimeout(typingTimeout);fetch(API18+'/api/typing',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+getToken()},body:JSON.stringify({chatId:currentChatId})});typingTimeout=setTimeout(()=>{},3000)}

console.log('[Tribal AI v18.0] Frontend loaded: folders, search, quick-replies, api-keys, export, scheduled, tags, undo, regenerate, metrics');
